// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhWnbPQE_uubUeohPx8qUsFPg4jo_bPYk',
    appId: '1:414674077860:web:f06fc016bb733eabfdfe31',
    messagingSenderId: '414674077860',
    projectId: 'act13-928ac',
    authDomain: 'act13-928ac.firebaseapp.com',
    storageBucket: 'act13-928ac.firebasestorage.app',
    measurementId: 'G-PSFYZSJYJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbkNzymCl6pc9L_X88nPoQw1sjK6tg1S4',
    appId: '1:414674077860:android:4667827aae79ea93fdfe31',
    messagingSenderId: '414674077860',
    projectId: 'act13-928ac',
    storageBucket: 'act13-928ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwl02GZn0x_EPdWBEgRLksqE3tkcdrAlo',
    appId: '1:414674077860:ios:1a6300e4ced9a8a8fdfe31',
    messagingSenderId: '414674077860',
    projectId: 'act13-928ac',
    storageBucket: 'act13-928ac.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwl02GZn0x_EPdWBEgRLksqE3tkcdrAlo',
    appId: '1:414674077860:ios:1a6300e4ced9a8a8fdfe31',
    messagingSenderId: '414674077860',
    projectId: 'act13-928ac',
    storageBucket: 'act13-928ac.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhWnbPQE_uubUeohPx8qUsFPg4jo_bPYk',
    appId: '1:414674077860:web:1e5a7621c349f935fdfe31',
    messagingSenderId: '414674077860',
    projectId: 'act13-928ac',
    authDomain: 'act13-928ac.firebaseapp.com',
    storageBucket: 'act13-928ac.firebasestorage.app',
    measurementId: 'G-7N4296DZQH',
  );
}
